# Site settings
title: Pyppe.fi
email: pyppe@iki.fi
description: "Pyppe.fi (Pyry-Samuli Lahti)"
baseurl: ""
url: "https://www.pyppe.fi"
sitemap_pages:
  - /
  - /frontpage/
  - /elamantarina/
  - /life-story/
exclude:
  - .idea
  - .sass-cache
  - .tweet-cache
  - node_modules
  - src

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:title/
excerpt_separator: <!--more-->
gems: [jekyll-paginate]
paginate: 10
paginate_path: '/blog/:num/'
