# Site settings
title: Pyppe.fi
email: pyppe@iki.fi
description: "Pyppe.fi (Pyry-Samuli Lahti)"
baseurl: ""
url: "http://www.pyppe.fi"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:title/
highlighter: pygments
excerpt_separator: <!--more-->
paginate: 10
paginate_path: '/blog/:num/'
